name: firestore_example
description: Demonstrates how to use the cloud_firestore_mocks plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.0

dev_dependencies:
  test: any
  flutter_driver:
    sdk: flutter
  fake_cloud_firestore:
    path: ../

flutter:
  uses-material-design: true
