name: cloud_firestore_mocks
description: Fake implementation of Cloud Firestore. Use this package to write unit tests involving Cloud Firestore.
version: 0.4.3
homepage: http://blog.wafrat.com
repository: https://github.com/atn832/cloud_firestore_mocks

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.1+1
  cloud_firestore_platform_interface: ^1.0.0
  plugin_platform_interface: ^1.0.1
  mockito: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.0.0
  test: ^1.3.0
