name: fake_cloud_firestore
description: Previously known as cloud_firestore_mocks. Fake implementation of Cloud Firestore. Use this package to unit test apps that use Cloud Firestore.
version: 4.0.1
homepage: https://www.wafrat.com
repository: https://github.com/atn832/fake_cloud_firestore

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.0
  cloud_firestore_platform_interface: ^7.0.0
  collection: ^1.14.13
  plugin_platform_interface: ^2.0.0
  quiver: ^3.0.0
  rxdart: ^0.28.0
  mock_exceptions: ^0.8.2
  fake_firebase_security_rules: ^0.5.2
  rx: ^0.4.0
  equatable: ^2.0.5
  clock: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.15.2
  firebase_auth_mocks: ^0.15.0
  flutter_lints: ^6.0.0

false_secrets:
  - google-services.json
  - GoogleService-Info.plist
