name: cloud_firestore_mocks
description: Fake implementation of Cloud Firestore. Use this package to write unit tests involving Cloud Firestore.
version: 0.6.0
homepage: http://blog.wafrat.com
repository: https://github.com/atn832/cloud_firestore_mocks

environment:
  sdk: ">=2.9.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0
  cloud_firestore_platform_interface: ^4.0.0
  collection: ^1.14.13
  plugin_platform_interface: ^2.0.0
  mockito: ^4.1.1
  quiver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.9.0
  test: ^1.15.2
